---
language: python
services:
  - docker

env:
  global:
    - ROLE_NAME: meierw.jenkins_job_dsl_exec

install:
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv $TRAVIS_BUILD_DIR $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test
